version: 2

models:
  
  # --- DIMENSIONS ---
  - name: dim_customer
    description: "Customer dimension table"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null


  - name: dim_product
    description: "Product dimension table (Categories, names)"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_seller
    description: "Seller dimension table (Location data)"
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null


  # --- FACTS ---
  - name: fact_order_items
    description: "Transactional fact table at the order item grain"
    columns:
      # The Primary Key we created with MD5
      - name: order_item_sk
        tests:
          - unique
          - not_null

      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_orders')
              field: order_id
              
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_seller')
              field: seller_id

 
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id