ecom_transformation:
  outputs:
    dev:
      dbname: ecom_db
      host: localhost
      pass: postgres
      port: 8432
      schema: raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
